genius-invokation/genius-invokation

- packages/core/src/io.ts
- packages/pybinding/gitcg/__init__.py
- packages/pybinding/gitcg/player.py
- packages/pybinding/tests/test.py
- packages/webui-core/src/Chessboard.tsx
- proto/action.proto
Elevate `preview` and `required_cost` to `action` level
> protobuf adjustment

- packages/core/src/query/semantic.ts
- packages/test/__tests__/basic.test.tsx
- packages/test/__tests__/dice_deduct.test.tsx
- packages/test/__tests__/query_active_inc_defeated.test.tsx
- packages/test/__tests__/query_recent_opp_from.test.tsx
- packages/test/src/matchers.ts
> Fix recent opp from

- docs/development/data/events.md
- packages/core/src/base/skill.ts
- packages/core/src/builder/context/skill.ts
- packages/core/src/builder/skill.ts
- packages/data/src/commons.ts
- packages/data/src/old_versions/v4.8.0.ts
- packages/test/__tests__/bond_of_life.test.tsx
- packages/test/src/controller.ts
- packages/test/src/setup.ts
- Fix `Bond of life` implementation
- Add a new modify stage for upcoming `Clorinde`'s skill
- A unit test added
> Fix modify heal

- packages/server/src/rooms/rooms.service.ts
- packages/web-client/src/pages/Room.tsx
- Add `lock` for restarting server
- Add `ping` SSE per 30s
- Frontend small improvement
> `web-client` & `server` update

- packages/core/src/builder/skill.ts
- packages/test/__tests__/listen_to_all.test.tsx
- packages/test/src/controller.ts
> fix(core/builder): listenTo should use latest value

- packages/deck-builder/vite.config.ts
- packages/detail-log-viewer/vite.config.ts
- packages/standalone/vite.config.ts
- packages/webui-core/vite.config.ts
- packages/webui/vite.config.ts
As a workaround (what?) for solidjs/vite-plugin-solid#171 .
> fix(vite): fix dev server bug

- packages/core/src/skill_executor.ts
- packages/test/__tests__/damage_combination.test.tsx
> feat(core): Add damage combination to `SkillExecutor`

- packages/core/src/base/skill.ts
- packages/core/src/game.ts
- packages/core/src/io.ts
- packages/core/src/preview.ts
- packages/core/src/utils.ts
- packages/pybinding/src/gitcg/__init__.py
- packages/pybinding/tests/test.py
- packages/test/src/controller.ts
- packages/typings/src/index.ts
- packages/utils/src/dice.ts
- packages/webui-core/src/Chessboard.tsx
- proto/action.proto
... to provide more hint and preview data
> feat(core): includes invalid action in rpc

- .github/workflows/sync_beta.yml
Reverts genius-invokation/genius-invokation#152
> Revert "chore(ci): use GitHub CLI"

- packages/web-ui-core/src/components/Image.tsx
- packages/web-ui-core/src/components/StatusGroup.tsx
> feat(web-ui-core): no altText in status

- packages/assets-manager/scripts/generate_names.ts
- packages/assets-manager/src/index.ts
- packages/assets-manager/src/manager.ts
- packages/assets-manager/src/names.ts
- packages/card-data-viewer/src/Description.tsx
- packages/card-data-viewer/src/Entity.tsx
> fix(assets-manager): remove KEYWORD_ID_OFFSET

- packages/server/src/rooms/rooms.service.ts
- packages/web-client/src/pages/Room.tsx
> feat(server): add reliability; fixes #159

- packages/core/src/game.ts
- packages/core/src/skill_executor.ts
- packages/test/__tests__/albedo.test.tsx
> fix(core): correct plunging attack

- packages/core/src/builder/context/skill.ts
> fix(core): technique damage is also main damage

- packages/server/src/rooms/rooms.controller.ts
- packages/server/src/rooms/rooms.service.ts
- packages/web-client/src/pages/Room.tsx
> feat(server/web-client): fixes #210

- packages/server/src/rooms/rooms.controller.ts
- packages/server/src/rooms/rooms.service.ts
- packages/web-client/src/pages/Room.tsx
Reverts genius-invokation/genius-invokation#232
> Revert "feat(server/web-client): fixes #210"

- packages/core/src/builder/entity.ts
Change-Id: I0a2273dd1d27937533af77010d1b740b0ea2126e
> fix(core): character area entity on defeated priority

- packages/data/src/characters/cryo/eula.ts
- packages/legacy-web-ui-core/src/Entity.tsx
- packages/web-ui-core/src/components/Entity.tsx
small fix on eula and reverse the sequence to make sure no bug on display
> some bug fixed

- packages/core/src/builder/context/skill.ts
Change-Id: I46632f1f98ea4f7672d40d4bc6d10bd6c0975c27
> fix(core): convertDice while player.dice.length is smaller

- packages/core/src/base/mutation.ts
- packages/core/src/base/state.ts
- packages/core/src/builder/skill.ts
- packages/core/src/game.ts
- packages/core/src/skill_executor.ts
- packages/test/src/setup.ts
> fix(core): move delayedSkill from builder to executor

- packages/core/src/base/mutation.ts
- packages/core/src/builder/context/skill.ts
- packages/core/src/game.ts
- packages/core/src/io.ts
- packages/core/src/mutator.ts
- packages/core/src/preview.ts
- packages/core/src/skill_executor.ts
- packages/typings/src/index.ts
- packages/web-ui-core/src/action.ts
- packages/web-ui-core/src/components/CharacterArea.tsx
- packages/web-ui-core/src/components/Entity.tsx
- packages/web-ui-core/src/components/VariableDiff.tsx
- packages/web-ui-core/src/dev.tsx
- proto/mutation.proto
fixes #166
Change-Id: I3ebc1ec92cc11961dd6cab47821a1b1d83870626
> fix(core,web-ui-core): Add direction for ModifyVariable mutation

- packages/deck-builder/src/AllCards.tsx
- packages/deck-builder/src/AllCharacterCards.tsx
Reverts genius-invokation/genius-invokation#278
> Revert "feat(deck-builder): change the icon size and the version sequence"

- packages/web-client/src/components/Footer.tsx
> feat(web-client): the year

- packages/core/src/game.ts
- packages/core/src/skill_executor.ts
- packages/test/__tests__/plunging.test.tsx
> fix(core): plunging attack

- packages/data/src/characters/electro/beidou.ts
- packages/data/src/characters/hydro/alldevouring_narwhal.ts
- packages/data/src/characters/hydro/furina.ts
- packages/data/src/characters/hydro/mona.ts
- packages/data/src/characters/hydro/sangonomiya_kokomi.ts
> fix(data): multiple bugs

- packages/data/src/characters/electro/electro_hypostasis.ts
see title
no need, just see CI
> fix(data): electro_hypostasis summon addDice UsagePerRound

- packages/assets-manager/src/manager.ts
- packages/assets-manager/src/static_deck_data.ts
- packages/config/src/index.ts
- packages/server/src/rooms/rooms.service.ts
- packages/static-data/scripts/action_cards.ts
- packages/static-data/scripts/characters.ts
- packages/static-data/scripts/entities.ts
- packages/static-data/scripts/utils.ts
- packages/static-data/src/data/characters.json
- packages/static-data/src/data/entities.json
- packages/web-client/src/components/DeckBriefInfo.tsx
- packages/web-client/src/pages/Room.tsx
- packages/web-ui-core/src/components/Chessboard.tsx
- packages/web-ui-core/src/components/Image.tsx
- packages/web-ui-core/src/components/RerollDiceView.tsx
- packages/web-ui-core/src/dev.tsx
- packages/web-ui-core/src/standalone.tsx
> feat(assets-manager): use assets api v3

- packages/card-data-viewer/src/Entity.tsx
- packages/card-data-viewer/src/style.css
- packages/web-ui-core/src/action.ts
- packages/web-ui-core/src/async_queue.ts
- packages/web-ui-core/src/client.tsx
- packages/web-ui-core/src/components/ActionHintText.tsx
- packages/web-ui-core/src/components/Chessboard.tsx
- packages/web-ui-core/src/components/ChessboardBackground.tsx
- packages/web-ui-core/src/components/DicePanel.tsx
- packages/web-ui-core/src/components/Entity.tsx
- packages/web-ui-core/src/components/Image.tsx
- packages/web-ui-core/src/components/NotificationBox.tsx
- packages/web-ui-core/src/components/PlayerInfo.tsx
- packages/web-ui-core/src/components/RerollDiceView.tsx
- packages/web-ui-core/src/components/RoundAndPhaseNotification.tsx
- packages/web-ui-core/src/components/SkillButtonGroup.tsx
- packages/web-ui-core/src/components/VariableDiff.tsx
- packages/web-ui-core/src/dev.tsx
- packages/web-ui-core/src/layout.ts
- packages/web-ui-core/src/primitives/key_with_animation.ts
- packages/web-ui-core/src/style.css
- packages/web-ui-core/src/ui_state.ts
- packages/web-ui-core/src/vite-env.d.ts
卡牌详情尺寸修改
卡牌详情角色大头修改
卡牌详情child图片对齐方式修改
行动后提示板美术修改
Image类参数修改
playerinfo无图模式优化了对齐
> feat(web-ui, card-data-viewer): UI adjustment

- packages/web-client/src/config.ts
See [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Location/origin)
> style(web-client): use location.origin as SERVER_HOST fallback

- packages/core/src/__tests__/utils.test.ts
- packages/core/src/base/character.ts
- packages/core/src/base/mutation.ts
- packages/core/src/base/skill.ts
- packages/core/src/builder/card.ts
- packages/core/src/builder/character.ts
- packages/core/src/builder/context/skill.ts
- packages/core/src/builder/entity.ts
- packages/core/src/builder/skill.ts
- packages/core/src/game.ts
- packages/core/src/io.ts
- packages/core/src/mutator.ts
- packages/core/src/skill_executor.ts
- packages/core/src/utils.ts
- packages/data/src/characters/hydro/hydro_hilichurl_rogue.ts
- packages/test/__tests__/hydro_hilichurl_rogue.test.tsx
顺便修个水丘丘
Change-Id: I567cf792f60c7ef7d68e307a2a451a5bb329ba5b
> feat(core): update core preparing next version

- packages/server/src/auth/auth.controller.ts
- packages/web-client/index.html
- packages/web-client/public/manifest.json
- packages/web-client/src/App.tsx
- packages/web-client/src/components/Header.tsx
- packages/web-client/src/components/Login.tsx
- packages/web-client/src/components/RoomDialog.tsx
- packages/web-client/src/components/RoomInfo.tsx
- packages/web-client/src/pages/EditDeck.tsx
- packages/web-client/src/pages/Home.tsx
- packages/web-client/src/pages/Room.tsx
- packages/web-client/src/style.css
Reverts genius-invokation/genius-invokation#328
> Revert "feat(web-client): PWA improvement"

- packages/core/src/builder/context/character.ts
- packages/core/src/builder/context/skill.ts
- packages/data/src/cards/event/legend.ts
- packages/data/src/cards/event/other.ts
- packages/data/src/cards/support/ally.ts
- packages/data/src/characters/anemo/dvalin.ts
- packages/data/src/characters/anemo/kaedehara_kazuha.ts
- packages/data/src/characters/anemo/sayu.ts
- packages/data/src/characters/anemo/wanderer.ts
- packages/data/src/characters/dendro/baizhu.ts
- packages/data/src/characters/dendro/kinich.ts
- packages/data/src/characters/electro/abyss_lector_violet_lightning.ts
- packages/data/src/characters/geo/azhdaha.ts
- packages/data/src/characters/geo/kachina.ts
- packages/data/src/commons.ts
- packages/data/src/old_versions/v3.3.0.ts
- packages/data/src/old_versions/v4.1.0.ts
- packages/data/src/old_versions/v4.2.0.ts
- packages/data/src/old_versions/v4.7.0.ts
Change-Id: Ida2cebf3fe9be5cf6ae22eca5518dec15bfc61ce
> fix(core, data): change next/prev query sematic

- packages/web-ui-core/src/components/CharacterArea.tsx
> fix(web-ui-core): adjust selecting icon z-index to be above of defeated

- packages/assets-manager/src/manager.ts
- packages/web-ui-core/src/components/CharacterArea.tsx
- packages/web-ui-core/src/style.css
- packages/web-ui-core/src/svg/ArtifactIcon.svg
- packages/web-ui-core/src/svg/DamageIcon.svg
- packages/web-ui-core/src/svg/TalentIcon.svg
- packages/web-ui-core/src/svg/WeaponIcon.svg
- packages/web-ui-core/vite.config.ts
上传了assets-manager-v3修复
增加了天赋/武器/圣遗物svg
增加了特技图标
禁用了svg压缩
damage.svg内部采用了更长的id防止混淆
> feat(web-ui): equipment-icon

- packages/data/src/cards/support/ally.ts
- packages/test/__tests__/delayed_triggering.test.tsx
Change-Id: Ie9c31b7a15e98bb5d6398fbe8331e89fdc168ace
> fix(data): 常九爷 & 拉娜

- README.md
> approve-test

- packages/web-ui-core/src/components/CharacterArea.tsx
> fix(web-ui): hpicon-offset

- packages/web-client/src/pages/Room.tsx
- packages/web-ui-core/src/client.tsx
- packages/web-ui-core/src/components/Chessboard.tsx
- packages/web-ui-core/src/components/PlayerInfoBox.tsx
> feat(web-ui): end game button

- .vscode/settings.json
- packages/web-ui-core/src/components/Chessboard.tsx
> fix(web-ui-core): skill selecting should keep viewer

- packages/web-ui-core/src/components/Chessboard.tsx
- packages/web-ui-core/src/components/CurrentTurnHint.tsx
- packages/web-ui-core/src/components/DeclareEndMarker.tsx
- packages/web-ui-core/src/components/MutationViewer.tsx
- packages/web-ui-core/src/components/RerollDiceView.tsx
- packages/web-ui-core/src/components/SelectCardView.tsx
- packages/web-ui-core/src/components/SpecialViewToggleButton.tsx
- packages/web-ui-core/src/components/SwitchHandsView.tsx
- packages/web-ui-core/src/components/Timer.tsx
把数字计时器移到了右上角，换了个样式
20秒的时候还是会回到中间
动态计算右上角元素的位置，使间隔统一
> feat(web-ui): digital timer

- packages/data/src/characters/anemo/chasca.ts
> fix(data): chasca state trigger condition

- packages/card-data-viewer/src/dev.tsx
- packages/core/src/__tests__/utils.test.ts
- packages/core/src/io.ts
- packages/typings/src/common_enums.ts
- proto/state.proto
> feat(typings, core): add tag to Protobuf typing of CardState

- packages/web-ui-core/src/components/Card.tsx
- packages/web-ui-core/src/components/CharacterArea.tsx
- packages/web-ui-core/src/components/Entity.tsx
- packages/web-ui-core/src/components/HistoryViewer.tsx
- packages/web-ui-core/src/components/PlayingCard.tsx
- packages/web-ui-core/src/svg/CardFrameNormal.svg
- packages/web-ui-core/src/svg/CardFrameSummon.svg
> feat(web-ui): cardframe

- packages/core/src/io.ts
- packages/core/src/skill_executor.ts
- packages/data/src/characters/pyro/mavuika.ts
- proto/state.proto
Change-Id: I95389d10c7bd008c42d8f6ec0d66de2344d7068b
修复了击倒不清空战意的问题
**并没有实现和官方一致的充能判断**，目前我们仍然不清楚官方是怎么判断玛薇卡的充能的
> fix(core, data): fix mavuika spirit issue

- packages/web-ui-core/src/components/HistoryViewer.tsx
- packages/web-ui-core/src/history/parser.ts
fix天赋牌分类
fix元素附着预览不显示
fix元素附着文本
> fix(web-ui): history

- packages/web-ui-core/src/components/Card.tsx
- packages/web-ui-core/src/components/CharacterArea.tsx
- packages/web-ui-core/src/components/Chessboard.tsx
- packages/web-ui-core/src/components/Entity.tsx
- packages/web-ui-core/src/components/HistoryViewer.tsx
- packages/web-ui-core/src/components/PlayingCard.tsx
- packages/web-ui-core/src/style.css
Change-Id: I0beca87898f2ece48eae0ffacae0ed0c537cfd91
> feat(web-ui-core): history backdrop

- packages/data/src/cards/support/item.ts
- packages/data/src/old_versions/v4.7.0.ts
> fix(data): kusava dispose 2-memory card

- packages/cbinding/CMakeLists.txt
> fix(cbinding): Update CMakeLists.txt

- packages/web-ui-core/src/components/SelectCardView.tsx
> feat(web-ui): select card dice cost

- packages/web-ui-core/src/components/Entity.tsx
> feat(web-ui): entity bottom hint

- packages/server/src/auth/auth.controller.ts
- packages/web-client/src/App.tsx
- packages/web-client/src/components/Login.tsx
- packages/web-client/src/pages/Home.tsx
Change-Id: Ib3744e80bc6523b62c0ef9f33d0abd03314c55bc
> feat(web-client, server): use popup for OAuth login

- packages/assets-manager/src/manager.ts
- packages/web-client/package.json
- packages/web-client/public/sw.js
- packages/web-client/src/components/DeckBriefInfo.tsx
- packages/web-client/src/index.tsx
- packages/web-client/src/pages/Decks.tsx
- packages/web-client/src/pages/Home.tsx
Change-Id: I25026a32ebbc5375ce5c8f660cab5d6061a1aa72
> feat(web-client, assets-manager): Cache assets

- packages/data/src/characters/dendro/kinich.ts
> fix(data): align to official settlement

- packages/web-ui-core/src/client.tsx
- packages/web-ui-core/src/dev.tsx
- packages/web-ui-core/src/history/parser.ts
> feat(web-ui): persistent history

- packages/web-client/src/App.tsx
> fix(web-client): router base url

- packages/web-ui-core/src/components/HistoryViewer.tsx
- packages/web-ui-core/src/components/PlayerInfoBox.tsx
- packages/web-ui-core/src/style.css
> fix(web-ui): playeriofo and scrollbar

- packages/core/src/builder/entity.ts
- packages/data/src/characters/geo/xilonen.ts
- packages/data/src/characters/hydro/sigewinne.ts
Change-Id: If7c5d9950cf0fd3a1608559479c023be1cecd4ea
fixes #413
> fix(core, data): noDefaultDispose

- packages/data/src/characters/dendro/emilie.ts
- packages/data/src/characters/dendro/kinich.ts
- packages/data/src/characters/pyro/arlecchino.ts
- packages/test/__tests__/emilie.test.tsx
fixes #157
Change-Id: I3706c0dccf63585d59e30136a5428086e2918c74
> fix(data): multiple data bugs

- packages/core/src/base/entity.ts
- packages/core/src/io.ts
- packages/data/src/commons.ts
- packages/typings/src/common_enums.ts
- packages/web-ui-core/src/components/CharacterArea.tsx
- packages/web-ui-core/src/dev.tsx
> feat(typings, core, web-ui-core): add bond-of-life tag

- packages/core/src/builder/context/skill.ts
> fix(core): diceCostOfCard

- packages/core/src/base/reaction.ts
- packages/core/src/base/skill.ts
- packages/core/src/builder/context/card.ts
- packages/core/src/builder/context/character.ts
- packages/core/src/builder/context/entity.ts
- packages/core/src/builder/context/reactive.ts
- packages/core/src/builder/context/reactive_base.ts
- packages/core/src/builder/context/skill.ts
- packages/core/src/builder/type.ts
- packages/core/src/mutator.ts
- packages/core/src/query/index.ts
> chore(core): improve Reactive State

- bun.lock
- packages/card-data-viewer/package.json
- packages/deck-builder/package.json
- packages/detail-log-viewer/package.json
- packages/web-client/package.json
- packages/web-ui-core/package.json
- packages/web-ui-core/src/components/Button.tsx
- packages/web-ui-core/src/style.css
尝试修复对战平台button激活范围过大bug
roompage有同名css类，给button里的group改个名
> fix(web-ui): button hover/active

- packages/static-data/scripts/entities.ts
- packages/static-data/scripts/properties.ts
- packages/static-data/src/data/entities.json
remainAfterDIe: 死亡不掉落
persistEffectType: 持续效果(蓝盾/黄盾/眩晕/冻结/石化/独立夜魂)
> feat(static-data): entiity add 2 new properties

- packages/web-ui-core/src/components/Card.tsx
- packages/web-ui-core/src/components/CharacterArea.tsx
- packages/web-ui-core/src/components/Chessboard.tsx
- packages/web-ui-core/src/components/Damage.tsx
- packages/web-ui-core/src/components/Entity.tsx
- packages/web-ui-core/src/components/PlayingCard.tsx
- packages/web-ui-core/src/style.css
- packages/web-ui-core/src/ui_state.ts
Change-Id: I8cef09c76e9621282290d21631e66a317f07e7df
> feat(web-ui-core): damage animation

- packages/core/src/base/skill.ts
- packages/core/src/builder/context/skill.ts
- packages/core/src/builder/skill.ts
- packages/core/src/mutator.ts
- packages/core/tsconfig.json
> fix(core): HCI condition of reason

- bun.lock
- packages/card-data-viewer/tsconfig.json
- packages/static-data/tsconfig.json
- packages/web-client/package.json
- packages/web-ui-core/package.json
- packages/web-ui-core/scripts/svg_render.ts
- packages/web-ui-core/src/components/CharacterArea.tsx
- packages/web-ui-core/src/components/Chessboard.tsx
- packages/web-ui-core/src/components/DiceCost.tsx
- packages/web-ui-core/src/style.css
Change-Id: I4eb3ae9b2d019f7b476ccea61afa7035c9dc541b
> fix(web-ui-core): isolate styling, unexpected refresh

- packages/web-ui-core/src/action.ts
- packages/web-ui-core/src/components/CharacterArea.tsx
- packages/web-ui-core/src/components/Entity.tsx
- packages/web-ui-core/tsconfig.json
Change-Id: I2dd4485377e26b143deb68879dc60c77d0bbce6a
> feat(web-ui): preview negative health

- packages/core/src/base/skill.ts
- packages/core/src/builder/skill.ts
- packages/data/src/commons.ts
Change-Id: I9151422c7f9b5acbcc4035f91be80cb10bc48a96
> fix(core): immuneDefeated/revive heal should be unmodifiable

- packages/core/src/base/state.ts
- packages/core/src/game.ts
- packages/core/src/preview.ts
Change-Id: I16c587d78632cd04001aaac558c7898911991078
> feat(core): configurable error level

- packages/core/src/base/entity.ts
- packages/data/src/cards/event/other.ts
- packages/data/src/cards/support/ally.ts
- packages/data/src/cards/support/place.ts
Change-Id: I705a3604662a57a268b417c28b66f94323951893
> chore(core, data): use simulanka tag

- packages/core/src/builder/entity.ts
> fix(core): auto disposing nightsoul happens on beforeAction

- packages/core/src/base/skill.ts
- packages/core/src/builder/skill.ts
- packages/data/src/characters/pyro/mavuika.ts
> fix(data): mavuika 'cancel' consume value

- packages/data/src/cards/event/food.ts
- packages/data/src/characters/cryo/wriothesley.ts
- packages/data/src/characters/electro/consecrated_scorpion.ts
- packages/data/src/old_versions/v3.3.0.ts
> fix(data): seems fixing

- packages/core/src/base/skill.ts
- packages/core/src/builder/skill.ts
- packages/core/src/mutator.ts
- packages/test/__tests__/the_mausoleum_of_king_deshret.test.tsx
Change-Id: I6d365ede012115cf8ec1e3320ac8903f50d77271
> fix(core): allow overflow on HCI

- packages/core/src/game.ts
> fix(core): 下落攻击行为对齐

- packages/web-ui-core/src/components/Chessboard.tsx
- packages/web-ui-core/src/components/CurrentTurnHint.tsx
- packages/web-ui-core/src/components/FullScreenToggleButton.tsx
- packages/web-ui-core/src/components/HistoryViewer.tsx
- packages/web-ui-core/src/components/Timer.tsx
- packages/web-ui-core/src/svg/FullScreen.svg
- packages/web-ui-core/src/svg/HistoryIcon.svg
- packages/web-ui-core/src/svg/NormalScreen.svg
- packages/web-ui-core/src/svg/VisibilityIcon.svg
添加全屏按钮
将右上角按钮样式全部统一为最新（与“直播模式”文字标签样式相同）
> feat(web-ui): add fullscreen button

- packages/data/src/characters/dendro/nahida.ts
- packages/test/__tests__/nahida.test.tsx
Change-Id: I8882a394f6bd83dd799b1be87cfc12aa70234b5f
> fix(data): nahida seed effect

- packages/web-ui-core/src/components/Entity.tsx
> feat(web-ui): hide hint preview when creating entity

- packages/data/src/cards/event/other.ts
- packages/data/src/cards/support/ally.ts
> fix(data): PucasSupport add allies list

- packages/cbinding/js/main.ts
> Fix the “state from json” bug

- packages/data/src/characters/dendro/kaveh.ts
> fix(data): kaveh talent listen range

- packages/core/src/base/skill.ts
- packages/core/src/builder/context/skill.ts
- packages/core/src/skill_executor.ts
> feat(core): async adventure

- packages/data/src/characters/pyro/lord_of_eroded_primal_fire.ts
Change-Id: I430219d529123f199a833058fefcbf13c63c91a9
> fix(data): add abortPreview to 斫劫源焰

- bun.lock
- packages/assets-manager/package.json
- packages/assets-manager/src/index.ts
- packages/assets-manager/src/manager.ts
- packages/assets-manager/tsconfig.json
- packages/config/src/index.ts
- packages/web-client/public/sw.js
- packages/web-client/src/components/RoomDialog.tsx
更新 manager.ts
更新 sw.js
fix errors
> feat(assets-manager): Assets API v4 (#548)

- packages/core/src/builder/entity.ts
- packages/data/src/characters/dendro/eremite_floral_ringdancer.ts
- packages/data/src/characters/geo/arataki_itto.ts
- packages/data/src/characters/pyro/eremite_scorching_loremaster.ts
- packages/data/src/old_versions/v3.6.0.ts
- packages/data/src/old_versions/v5.0.0.ts
> fix(core/builder): add a warning about non-defaulted-name usage

- packages/assets-manager/src/manager.ts
- packages/assets-manager/tsup.config.ts
> feat(assets-manager): Make API Endpoint configurable at build time

- packages/core/src/base/entity.ts
- packages/core/src/builder/context/skill.ts
- packages/core/src/builder/entity.ts
> chore(core): move disposeWhenUsageIsZero to EntityDefinition
